spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/SOA-project
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: ApiGateway
server:
  port: 8092

jwt:
  auth:
    converter:
      resource-id: soa-project-rest-api
      principle-attribute: preferred_username