spring:
  profiles:
    active: dev
  application:
    name: ChatbotService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatbotDB
    username: adnane
    password: adnane
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8101

chatbot:
  api:
    url: https://rag-api-926019460727.us-central1.run.app
